# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

# Maven Package - create the function artifacts in
steps:
- task: Maven@2
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'
# Copy files    
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/azure-functions/**'
    TargetFolder: '$(build.artifactstagingdirectory)'
# Create Archive : zip file
- task: ArchiveFiles@2
  displayName: 'Archive $(build.artifactstagingdirectory)/target/azure-functions/$(functionAppMvnTargetFolder)'
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/target/azure-functions/$(functionAppMvnTargetFolder)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
# Deploy using Azure App Service Deploy - Webdeployment
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: javapipeline'
  inputs:
    azureSubscription: '$(azureSubcriptionKey)'
    appType: functionApp
    WebAppName: oplxcustsvcs-neu-dev-fop2
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    enableCustomDeployment: true
    DeploymentType: runFromZip    
    TakeAppOfflineFlag: false
    ExcludeFilesFromAppDataFlag: false
    RenameFilesFlag: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
